# Generated by Django 2.2.8 on 2019-12-30 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('cnp', models.CharField(default='', max_length=13)),
                ('id_series', models.CharField(default='', max_length=2)),
                ('id_number', models.CharField(default='', max_length=6)),
                ('issued_by', models.CharField(default='', max_length=20)),
                ('address_1', models.CharField(default='', max_length=100)),
                ('address_2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('county', models.CharField(default='', max_length=30)),
                ('postal_code', models.CharField(default='', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
