# Generated by Django 2.2.8 on 2020-01-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='candidates',
            field=models.ManyToManyField(related_name='candidates', to='voting.Candidate'),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='image',
            field=models.ImageField(default=True, upload_to='voting/static/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='voting/static/img'),
        ),
    ]
