# Generated by Django 2.2.8 on 2020-01-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('voting', '0003_auto_20200103_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='candidate_pics'),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='image',
            field=models.ImageField(upload_to='voting_pics'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Candidate')),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotingSession')),
            ],
        ),
    ]
