# Generated by Django 2.2.8 on 2020-01-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('voting', '0004_auto_20200104_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Vote')),
            ],
        ),
    ]
